/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author yesen
 */
public class Panel3C extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    public Panel3C() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloComercial = new javax.swing.JLabel();
        textNombreC = new javax.swing.JLabel();
        textComercialFNombre = new javax.swing.JTextField();
        textEdadC = new javax.swing.JLabel();
        textComercialFEdad = new javax.swing.JTextField();
        textSalarioC = new javax.swing.JLabel();
        textComerciaSalario = new javax.swing.JTextField();
        textComision = new javax.swing.JLabel();
        textComerciaFComision = new javax.swing.JTextField();
        btnSgteComerciaF = new javax.swing.JButton();

        tituloComercial.setText("COMERCIAL");

        textNombreC.setText("NOMBRE");

        textComercialFNombre.setToolTipText("Ej: Yesenia");

        textEdadC.setText("EDAD");

        textComercialFEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textComercialFEdadActionPerformed(evt);
            }
        });

        textSalarioC.setText("SALARIO");

        textComerciaSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textComerciaSalarioActionPerformed(evt);
            }
        });

        textComision.setText("COMISIÓN");

        textComerciaFComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textComerciaFComisionActionPerformed(evt);
            }
        });

        btnSgteComerciaF.setText("SIGUIENTE");
        btnSgteComerciaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSgteComerciaFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(btnSgteComerciaF)
                .addGap(261, 261, 261))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(tituloComercial))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNombreC)
                            .addComponent(textEdadC)
                            .addComponent(textSalarioC)
                            .addComponent(textComision))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textComerciaFComision, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textComerciaSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textComercialFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(textComercialFEdad)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(tituloComercial)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreC)
                    .addComponent(textComercialFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEdadC)
                    .addComponent(textComercialFEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSalarioC)
                    .addComponent(textComerciaSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnSgteComerciaF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textComision)
                    .addComponent(textComerciaFComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textComercialFEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textComercialFEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textComercialFEdadActionPerformed

    private void textComerciaSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textComerciaSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textComerciaSalarioActionPerformed

    private void textComerciaFComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textComerciaFComisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textComerciaFComisionActionPerformed

    private void btnSgteComerciaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSgteComerciaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSgteComerciaFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSgteComerciaF;
    private javax.swing.JTextField textComerciaFComision;
    private javax.swing.JTextField textComerciaSalario;
    private javax.swing.JTextField textComercialFEdad;
    private javax.swing.JTextField textComercialFNombre;
    private javax.swing.JLabel textComision;
    private javax.swing.JLabel textEdadC;
    private javax.swing.JLabel textNombreC;
    private javax.swing.JLabel textSalarioC;
    private javax.swing.JLabel tituloComercial;
    // End of variables declaration//GEN-END:variables
}

